name: Fund Report

on:
  schedule:
    - cron: '0 1 * * 1-5'
  workflow_dispatch:

jobs:
  push_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install akshare requests pandas
      - run: python3 query_fund.py
